spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8088" # the optional prefix won't fail the application in case cannot resolve the config server url
