server:
  port: 8082
  error:
    include-message: always # include Exception message in the HTTP response

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0 # 100% de tracing coverage